### ISSUE TITLE
Very different reports of idempotency check failures depending on the reason

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#221]
The issue https://github.com/tweag/topiary/issues/220 shows two different ways of getting Topiary to reach an idempotency check failure on OCaml code, one by making it yield un-parseable code in the first round, and another one by making it yield two different outputs in the two rounds.

However, those two idempotency check failures get reported very differently, and one of them has an output that looks more like unhandled exceptions and looks a bit scare, or might look scary for random users. See for yourself:

### Snippet 1

```ocaml
type t =
  { foo : bool [@default false];
    bar : float }
```
gives the output
```
Error: The formatter errored when trying to format the code twice (idempotence check).
This probably means that the formatter produced invalid code.
It would be helpful if you logged this error at https://github.com/tweag/topiary/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md
  Caused by: Parsing error between line 2, column 12 and line 2, column 13
```

### Snippet 2

```ocaml
type t =
  { foo : bool;
    bar : float [@default false] }
```
gives the output
```
[2023-02-01T19:06:28Z ERROR topiary] Failed idempotence check
thread 'main' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 type t = {
   foo: bool;
<  bar: float; [@default false]
>  bar: float;
>  [@default false]
 }
 

', src/lib.rs:180:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Actually, it has colours in my terminal:
![image](https://user-images.githubusercontent.com/5920602/216139895-8aafb2ac-7930-4db2-8054-a6c6d63c8d4d.png)

I think this one could be improved. The diff is not a bad thing, but `left` and `right` are not very informative and people might not know what the idempotency check is about. I would expect something closer to the first one, maybe:
```
Error: The formatter errored when trying to format the code twice (idempotence check).
This probably means that the formatter produced invalid code.
It would be helpful if you logged this error at https://github.com/tweag/topiary/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md
  Caused by: Difference between first and second rounds:
  Diff < first / second > :
   type t = {
     foo: bool;
  <  bar: float; [@default false]
  >  bar: float;
  >  [@default false]
   }
```
(The line stating that “this probably means that the formatter produced invalid code” should probably go away in that case.)

**Comment by torhovland** [comment]
The two different error messages are intentionally so, and was due to #112. But I agree that the second error message has room for improvement.

**Comment by Xophmeister** [comment]
The `left` and `right` terminology is hardcoded into the [`pretty_assertions` crate](https://github.com/rust-pretty-assertions/rust-pretty-assertions/blob/27ee62821f4c812e56484c9cc73ff7f27382a02a/pretty_assertions/src/printer.rs#L24-L25). However, you can output the diff, rather than panicking, to make the error look a little less scary:

![image](https://user-images.githubusercontent.com/384987/216981410-47a51f06-5c40-4066-926c-06e69b1387ff.png)

I think this is better and _probably_ good enough, without reimplementing the colourised diff from `pretty_assertions`.

---

Note: The OCaml examples in the OP issue do not cause idempotency errors any more; at least as of a204fe87420f8ea. The following Bash example still fails, and will do until #200 is solved:
```bash
{
  cat <<EOF
No indent
EOF
}
```
