### ISSUE TITLE
Idempotency check failure on lists with final semi-colon before final comment

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#243]
As of f97a163, Topiary throws an idempotency error on:

```ocaml
let foo =
  [
    bar; (* comment *)
    bar; (* comment *)
  ]
```
because the first pass produces:
```ocaml
let foo =
  [
    bar; (* comment *)
    bar; (* comment *);
  ]
```
with one semi-colon before *and* one semi-colon after the last comment.

## Bonus: various combinations

...of semi-colons before/after comments and of lists with/without a final semi-colon.

### Snippet 1: semi-colons before comments
```ocaml
let foo =
  [
    bar; (* comment *)
    bar; (* comment *)
  ]
```
triggers the idempotency check mentioned above.

### Snippet 2: semi-colons before comments, no final semi-colon
```ocaml
let foo =
  [
    bar; (* comment *)
    bar (* comment *)
  ]
```
gets formatted as
```ocaml
let foo =
  [
    bar; (* comment *)
    bar (* comment *);
  ]
```
with one semi-colon before and one semi-colon after the comment. The inconsistency is puzzling, and I thought there was a sort of rule not to put semi-colons after comments.

### Snippet 3: semi-colons after comments
```ocaml
let foo = 
  [
    bar (* comment *);
    bar (* comment *);
  ]
```
does not change, the semi-colons remaining after the comments.

### Snippet 4: semi-colons after comments, no final semi-colon
```ocaml
let foo =
  [
    bar (* comment *);
    bar (* comment *)
  ]
```
gets formatted as snippet 3, with semi-colons after the comments.

**Comment by nbacquey** [comment]
I honestly see no immediate way of fixing this.
The problem is that the syntax tree for lists is very flat, and there can be almost anything at top-level, between semicolons.
This makes the definition of a _non-comment node_ in that context quite tedious, contrary to what happens in records (where a non-comment node is either `field_definition` or `attribute`).

My proposed solution would be to add some heavy pre-processing and post-processing on the syntax tree, something like "remove all comments, move stuff around, then put back the comments at the correct place", but I'm not even sure of the feasibility.
