### ISSUE TITLE
Idempotency error on lists containing `let .. in`.

### ISSUE THREAD

**Issue by Niols** [tweag/topiary#244]
potentially linked to #243?

As of f97a163, Topiary throws an idempotency check error on
```ocaml
let foo =
  [
    let x = y in z
  ]
```
because the first phase formats it as:
```ocaml
let foo =
  [
    let x = y in z;
  ]
```
which the second phase then formats as:
```ocaml
let foo =
  [
    let x = y in z; ;
  ]
```

Fun facts:

- The latter is actually valid OCaml, if I'm not mistaken, and is the singleton list containing `let x = y in z`.
- After reaching these two semi-colons, Topiary becomes idempotent again and does not add more semi-colons.
- This only happens in multi-line mode. The single line expression:
  ```ocaml
  let foo = [let x = y in z]
  ```
  gets formatted as:
  ```ocaml
  let foo = [ let x = y in z]
  ```
  which has a tiny spacing issue but is fine otherwise.

**Comment by nbacquey** [comment]
We have a real conundrum here.
The problem is that
```ocaml
[
  let x = y in z;
]
```
gets interpreted as
```
{ Node list_expression }
  { Node [ }
  { Node let_expression }
    { Node value_definition }
      { Node let }
      { Node let_binding }
        { Node value_name }
        { Node = }
        { Node value_path }
          { Node value_name }
    { Node in }
    { Node sequence_expression }
      { Node value_path }
        { Node value_name }
      { Node ; }
  { Node ] }
```
That is, the semicolon is parsed as a _sequence delimiter_, and not as a _list element delimiter_. So naturally, when Topiary parses the code a second time, it adds the missing semicolon.
The only solution I see would be to format the original code as
```ocaml
[
  (let x = y in z);
]
```
However:
- this is a bit visually shocking,
- this will cause other idempotency issues if the parenthesized expression is multi-line
- it will have an even worse interaction with comments than what we already have

**Comment by nbacquey** [comment]
Both this issue and #243 clearly need addressing before the release of v0.1, and the only way I see it happening is if we stop enforcing the final delimiter on lists and arrays.
@aspiwack @torhovland @Xophmeister, what's your take on this?

**Comment by aspiwack** [comment]
We should normalise final delimiters. But maybe there is an argument that we can't quite yet and should drop it for v0.1

Some thoughts:
- I went and checked: the tree-sitter grammar is correct: this `;` is parsed as a sequence delimiter.  In particular `[let x = 1 in x; ;]` (space required) is parsed as a list of one element (you can't add a third `;` though, which makes me a little bit sad).
- As such it is _of prime importance_ that if we add a `;` after a `let`-expression, we parenthesise it: it needs to be `(let x = y in z);`. Otherwise, when adding an extra element
  ```ocaml
  [
    let x = y in z;
    "skippy the wonderdog";
  ]
  ```
  Would, confusingly, be a single-element list! (Here I can add as many exclamation marks as I wish, so here are three more: !!!)
- We also probably should think of how we normalise statement sequences. I assume that the right way is to _remove_ a terminal semicolon there, as imperfect as it is, since 1/ there is no natural place to add a final delimiter 2/ we expect standard Ocaml code to have no semicolon. It's not fully necessary to normalise such final semicolon, as they are unlikely to be written to begin with. Except in lists like this, maybe, in which case they would almost always be a mistake (we only catch the case when the final statement is a `let`, but it's a start).

@nbacquey why are you afraid that the parenthesised version be failing to be idempotent in multiline settings?

**Comment by nbacquey** [comment]
Even if we succeed at tagging the last element of the list (and I'm really not sure how to do that, see https://github.com/tweag/topiary/issues/243#issuecomment-1421038366), we cannot simply surround it with parenthesis.
For instance,
```ocaml
let _ =
  [
    let x = y in
    z
  ]
```
would get formatted as
```ocaml
let _ =
  [
    (let x = y in
    z);
  ]
```
which isn't correctly formatted itself ; the correct format would be
```ocaml
let _ =
  [
    (
      let x = y in
      z
    );
  ]
```
However, to directly go from the first piece of code to the third one, we would need to check whether the encompassed node is multi-line.
Topiary isn't currently able to do that: it can only currently check the multi-lined-ness of a node containing a softline, or a node in a custom scope (and there are no correct nodes to which we could attach custom scope markers).

**Comment by aspiwack** [comment]
I think that the problem you are outlining is that we want the query to be called on the modified syntax tree, so that appropriate newlines are inserted. Alternatively, is it possible to duplicate the logic of parenthesised expression and inline it where we want to add parentheses? (I'm not saying it's a good idea, but it's good to know what is available to us).
