### ISSUE TITLE
No longer failing on unknown capture name

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#364]
**Describe the bug**
The following code doesn't seem to do anything:

```rust
            // Return a query parsing error on unknown capture names
            unknown => {
                return Err(FormatterError::Query(
                    format!("@{unknown} is not a valid capture name"),
                    None,
                ))
            }
```

A test is needed to cover this case.

**To Reproduce**
This query should provoke the above error message:

```
(dynamic_type) @hello
```

**Expected behavior**
Error message expected.

**Comment by aspiwack** [comment]
Note (from a side-channel discussion), that it's not clear what the behaviour should be on unknown queries. We may want to let formatter authors use their own capture for use within the query file (see for instance https://github.com/tweag/topiary/pull/354#issuecomment-1473618331).

An option brought up by @ErinvanderVeen would be to have a naming convention to allow for author-defined captures, while also raising an error when a built-in capture is misspelt.

**Comment by Xophmeister** [comment]
It turns out that it's not simply "working" vs. "not working". The error shows -- i.e., the code path mentioned in the OP runs -- _only_ when a query that uses the unknown capture name matches something in the input source. If a query with an unknown capture name is never matches, you won't see the error.

For example, if your query looks like this:

```scm
(#language! json)
"{" @this_is_not_the_name_youre_looking_for
```

...then:
```console
$ topiary -q repro.scm <<< '"foo"'
"foo"
```

However:
```console
$ topiary -q repro.scm <<< '{}'
[2023-03-17T12:07:05Z ERROR topiary] @this_is_not_the_name_youre_looking_for is not a valid capture name
```

Note: The same behaviour occurs in the Wasm playground.
