### ISSUE TITLE
Fix Nix Mix

### ISSUE THREAD

**Issue by torhovland** [tweag/topiary#375]
**Describe the bug**
The Nix build is currently reporting warnings like this:

```
trace: warning: crane cannot find name attribute in /nix/store/i70apg8wmqwaw1d20w56yr3hyjvr4f21-source/Cargo.toml, consider setting `pname = "...";` explicitly
trace: warning: crane cannot find version attribute in /nix/store/i70apg8wmqwaw1d20w56yr3hyjvr4f21-source/Cargo.toml, consider setting `version = "...";` explicitly
```

**To Reproduce**

```
nix build
```

**Expected behavior**

No warnings or errors.

**Additional context**

https://github.com/ipetkov/crane/pull/237#issuecomment-1473931031

**Comment by Niols** [comment]
I don't know how things work in Nix wrt Cargo, but I would tend to blame the fact that `pname` is set but not `version` [here](https://github.com/tweag/topiary/blob/1b0eb9392d586afb9a7800c63f6418e55b03405f/default.nix#L83) and [here](https://github.com/tweag/topiary/blob/1b0eb9392d586afb9a7800c63f6418e55b03405f/default.nix#L102). Since `name` is `pname`+`version`, that should lead to the two errors above.

**Comment by torhovland** [comment]
See also this: https://github.com/ipetkov/crane/issues/281
