### ISSUE TITLE
`--in-place` and `--output-file` options fail if `/tmp` is on a different filesystem

### ISSUE THREAD

**Issue by nbacquey** [tweag/topiary#406]
**Describe the bug**
If the temporary file directory is mounted on a different file system than the output file (or input file if `--in-place` is used), then topiary will fail with:
```
[2023-04-03T08:00:27Z ERROR topiary] Could not persist output to disk
[2023-04-03T08:00:27Z ERROR topiary] Cause: Invalid cross-device link (os error 18)
```

**To Reproduce**
```bash
$ sudo mkdir /mytemp
$ sudo mount -t tmpfs -o size=50m tmpfs /mytemp
$ TMPDIR=/mytemp/ topiary -if topiary/tests/samples/expected/json.json
[2023-04-03T08:41:16Z ERROR topiary] Could not persist output to disk
[2023-04-03T08:41:16Z ERROR topiary] Cause: Invalid cross-device link (os error 18)
```

**Expected behavior**
Having `$TMPDIR` on a different filesystem is standard, Topiary shouldn't fail if this happens.

**Environment**
Ubuntu 22.04 + `main` as of 2023-04-03 (https://github.com/tweag/topiary/commit/af1d6bd052caf0d7987f9a73456657b41742153f)

**Additional context**
From the [documentation of tempfile](https://docs.rs/tempfile/latest/tempfile/struct.NamedTempFile.html#method.persist):
> Note: Temporary files cannot be persisted across filesystems. Also neither the file contents nor the containing directory are synchronized, so the update may not yet have reached the disk when persist returns.

**Comment by vkleen** [comment]
It might just be impossible to atomically move a file into place across filesystems. Just imagine you're running topiary on files in NFS...

One possible avenue: `tempfile` provides `new_in` method instead of `new`. If we use `new_in` with the same base directory that the file to be formatted lives in, that should most likely be the same filesystem. Unless someone bind mounted the file to be formatted, in which case it seems reasonable to just give up 😅
