### ISSUE TITLE
Syntax highlighting in the playground

### ISSUE THREAD

**Issue by aspiwack** [tweag/topiary#543]
It would be nice to have syntax highlighting of code samples (both source and formatted) and of the queries in the playground.

Considering that we already load tree-sitter grammar for our language (and for Tree-sitter query files). It should, in principle, be natural to use these grammars for syntax highlighting.

**Comment by torhovland** [comment]
The ironic part is that the Ace editor component we are using [comes with highlighting](https://ace.c9.io/#nav=higlighter) for over 100 languages built-in, but it's not based on Tree-sitter. Instead it's based on [this specification](https://pcwalton.blogspot.com/2010/11/syntax-highlighting-specification.html).

So the _easiest_ way to do this would be to rely on their existing highlighting for most of our languages, and then define highlighting for Nickel and the Tree-sitter query language.

But perhaps we rather want to do it the hard way, using Tree-sitter?

**Comment by aspiwack** [comment]
If most of our languages come with an already existing syntax specification for Ace, then let's just do the easy thing first. And think about potential improvement based on tree-sitter grammars in the future. It is ironic, as you say, but having reasonable syntax highlighting is what matters, so the shortest path to there is what we ought to do.

**Comment by torhovland** [comment]
Now, even if we wanted to do it the hard way, it doesn't look feasible with this Ace editor. It really insists of defining highlighting using its Regex-based approach.

The question, then, is if we should be looking at alternative editor components, better now than later.

**Comment by aspiwack** [comment]
It doesn't cost much to do a little research. How did you choose Ace editor?

**Comment by torhovland** [comment]
I saw the Nickel playground uses it.

**Comment by aspiwack** [comment]
Fair enough :slightly_smiling_face: 

@amesgen (for Ormolu) and @yannham did you do research in webcomponents for code editing? If so could you share?

**Comment by torhovland** [comment]
Some options:

- Ace - A comprehensive web-based code editor that also includes powerful syntax highlighting capabilities.
- CodeMirror - A versatile text editor implemented in JavaScript for the browser. It's specialized for editing code and features over 100 languages.
- Monaco Editor - The code editor that powers VS Code, this provides syntax highlighting among many other features.
- Rainbow - A small, lightweight library for syntax highlighting.
- Rouge.js - A lightweight, simple and flexible JavaScript Syntax highlighting library that's easy to use and has a lot of language coverage.
- SHJS (Syntax Highlighting in JavaScript) - A JavaScript program which highlights source code passages in HTML documents.
- SyntaxHighlighter - A fully functional self-contained code syntax highlighter developed in JavaScript.
- Google's Prettify - An embeddable script that makes source-code "pretty" (readable) in HTML pages.
- Prism - Prism is a lightweight, extensible syntax highlighter, built with modern web standards in mind. It’s used in millions of websites, including some of those you visit daily.
- Refractor - Lightweight, robust, elegant virtual syntax highlighting using [Prism](https://github.com/PrismJS/prism).
- Highlight.js - Syntax highlighting for the Web
- React Syntax Highlighter - Syntax highlighting component for React using the seriously super amazing [lowlight](https://github.com/wooorm/lowlight) and [refractor](https://github.com/wooorm/refractor) by [wooorm](https://github.com/wooorm)

**Comment by torhovland** [comment]
Given that the Nickel team uses Ace and have implemented highlighting for it, and that the Tree-sitter query language probably can be sorted out with a lightly modified Scheme mode, perhaps Ace isn't such a bad choice after all. We can always fall back to plain text mode, which for now we may have to do for the new Ocamllex language.

**Comment by yannham** [comment]
Highlighting is tiring. We have no less than 6 grammars for Nickel:

- the LALRPOP one for the interpreter
- the Vim one for the vim plugin - at the time we started it, the tree-sitter builtin support in neovim wasn't exactly streamlined
- the emacs plugin where the community apparently prefers to have a bare-bone entry plugin and let people do more complex stuff if they want LSP or tree-sitter based highligting :man_shrugging: 
- The Ace.js syntax for the editor in the playground
- A Prism.js syntax for highlighting the code 
- The tree-sitter grammar for generic highligthing and Topiary

It's frustrating and annoying to maintain. On factor was that tree-sitter is not always fully integrated enough with editor to make it the default way (like, you need a recent version of neovim or to install third party plugins).

I believe I chose the Ace editor after a quick review of the existing solutions at the time, based on the features, on highlighting capabilities, the possibility to show errors directly in-code, and also probably not least based on which ones were a drop-in component (almost) in React/Gatsby, so that I could just write a few lines and get a working editor on the website. I also didn't have many days to spent on the website and although I've done some fullstack development a bit before, I wouldn't describe myself exactly as a web developer, so I might have cut corners or made suboptimal choices.

There is an [open issue](https://github.com/tweag/nickel-lang.org/issues/334) about replacing Ace.js with Monaco, in particular because we do an error messages mambo-jumbo to mimic LSP diagnostics by hand, but because Monaco is basically the VSCode engine, we might get full LSP features out of the box, and also re-use the VSCode extension highlighing. Oh, by the way, I forgot this one, so we actually maintain 7 different Nickel grammars...
