### ISSUE TITLE
Bash 0.19 no longer builds in Nix

### ISSUE THREAD

**Issue by toastal** [tweag/topiary#734]
**Describe the bug**
Submodule is gone so it doesn’t clone correctly

**To Reproduce**
Try to build 0.4.0 from Nixpkgs (doesn’t yet exist… trying to update)

**Expected behavior**
Newer versions seem to at least build, but why hasn’t the lockfile been updated in ages?

**Environment**
 - OS name + version: NixOS unstable
 - Version of the code: 0.4.0

**Additional context**

[^1]

[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

**Comment by ErinvanderVeen** [comment]
This has been a recurring theme with the bash tree-sitter grammar depending on bash itself. The lockfile hasn't been updated in ages because the bash grammar changed significantly, and we haven't had the time to update our queries.

The main issue regarding the current build failure is here: #702, I'll leave this issue open for the valuable regarding the bash update, but I think all further discussion about the savannah issue should go there.

Thank you!
